//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S5.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int COMCODIGO { get; set; }
        public string COMSTATUS { get; set; }
        public Nullable<int> CLICODIGO { get; set; }
        public Nullable<decimal> COMVALORBRUTO { get; set; }
        public Nullable<decimal> COMDESCONTOS { get; set; }
        public Nullable<decimal> COMVALORLIQUIDO { get; set; }
        public string COMACOMPANHANTES { get; set; }
        public string COMTRANSACAOID { get; set; }
        public System.DateTime COMDATA { get; set; }
        public Nullable<System.DateTime> COMDATAATUALIZACAO { get; set; }
        public string COMSTATUSPAGSEGURO { get; set; }
        public string COMFEEDBACKCLIENTE { get; set; }
        public Nullable<bool> COMVENDIDO { get; set; }
        public bool COMLANCADA { get; set; }
    }
}
