//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S5.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumo
    {
        public int Codigo { get; set; }
        public int CodigoReserva { get; set; }
        public int CodigoProduto { get; set; }
        public decimal Valor { get; set; }
        public int Quantidade { get; set; }
        public System.DateTime DataHora { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
