//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S5.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Consumoes = new HashSet<Consumo>();
        }
    
        public int Codigo { get; set; }
        public int CodigoCliente { get; set; }
        public int CodigoApartamento { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public decimal Valor { get; set; }
        public Nullable<int> QtdHospedes { get; set; }
    
        public virtual Apartamento Apartamento { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumo> Consumoes { get; set; }
    }
}
