//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int USUCODIGO { get; set; }
        public string USUNOME { get; set; }
        public string USULOGIN { get; set; }
        public string USUSENHA { get; set; }
        public string USUAMIGOS { get; set; }
        public string USUCONTINENTE { get; set; }
    }
}
