//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S6.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int AUDCODIGO { get; set; }
        public string AUDNOMETABELA { get; set; }
        public string AUDTIPO { get; set; }
        public int AUDCHAVE { get; set; }
        public System.DateTime AUDDATAATUALIZACAO { get; set; }
    }
}
