//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S6.Banco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdAbuDhabiTurS06Entities : DbContext
    {
        public bdAbuDhabiTurS06Entities()
            : base("name=bdAbuDhabiTurS06Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<DisponibilidadeAcomodacao> DisponibilidadeAcomodacao { get; set; }
        public virtual DbSet<Pacote> Pacote { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<TIPOACOMODACAO> TIPOACOMODACAO { get; set; }
    }
}
