//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S6.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacote
    {
        public int PACCODIGO { get; set; }
        public string PACNOME { get; set; }
        public string PACDESCRICAO { get; set; }
        public byte[] PACMINIATURA { get; set; }
        public byte[] PACBANNER { get; set; }
        public System.DateTime PACDATAINICIO { get; set; }
        public System.DateTime PACDATATERMINO { get; set; }
        public decimal PACVALOR { get; set; }
        public bool PACATIVO { get; set; }
        public bool PACPRINCIPAL { get; set; }
        public Nullable<int> MINCODIGO { get; set; }
    }
}
