// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

namespace Session1.Infra.Models;

public partial class Session1Context : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Data Source=.\WORLDSKILLSP1;Initial Catalog=Session1;Integrated Security=True;Encrypt=False;");
    }

    public virtual DbSet<Amenity> Amenities { get; set; }
    public virtual DbSet<Area> Areas { get; set; }
    public virtual DbSet<Attraction> Attractions { get; set; }
    public virtual DbSet<CancellationPolicy> CancellationPolicies { get; set; }
    public virtual DbSet<CancellationRefundFee> CancellationRefundFees { get; set; }
    public virtual DbSet<Coupon> Coupons { get; set; }
    public virtual DbSet<DimDate> DimDates { get; set; }
    public virtual DbSet<Item> Items { get; set; }
    public virtual DbSet<ItemAmenity> ItemAmenities { get; set; }
    public virtual DbSet<ItemAttraction> ItemAttractions { get; set; }
    public virtual DbSet<ItemPicture> ItemPictures { get; set; }
    public virtual DbSet<ItemPrice> ItemPrices { get; set; }
    public virtual DbSet<ItemType> ItemTypes { get; set; }
    public virtual DbSet<Transaction> Transactions { get; set; }
    public virtual DbSet<TransactionType> TransactionTypes { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserType> UserTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Attraction>(entity =>
        {
            entity.HasOne(d => d.Area)
                .WithMany(p => p.Attractions)
                .HasForeignKey(d => d.AreaID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Attractions_Areas");
        });

        modelBuilder.Entity<CancellationRefundFee>(entity =>
        {
            entity.HasOne(d => d.CancellationPolicy)
                .WithMany(p => p.CancellationRefundFees)
                .HasForeignKey(d => d.CancellationPolicyID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CancellationRefundFees_CancellationPolicies");
        });

        modelBuilder.Entity<DimDate>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasOne(d => d.Area)
                .WithMany(p => p.Items)
                .HasForeignKey(d => d.AreaID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Items_Areas");

            entity.HasOne(d => d.ItemType)
                .WithMany(p => p.Items)
                .HasForeignKey(d => d.ItemTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Places_PlaceTypes");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Items)
                .HasForeignKey(d => d.UserID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Places_Users");
        });

        modelBuilder.Entity<ItemAmenity>(entity =>
        {
            entity.HasOne(d => d.Amenity)
                .WithMany(p => p.ItemAmenities)
                .HasForeignKey(d => d.AmenityID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlaceAmenities_Amenities");

            entity.HasOne(d => d.Item)
                .WithMany(p => p.ItemAmenities)
                .HasForeignKey(d => d.ItemID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlaceAmenities_Places");
        });

        modelBuilder.Entity<ItemAttraction>(entity =>
        {
            entity.HasOne(d => d.Attraction)
                .WithMany(p => p.ItemAttractions)
                .HasForeignKey(d => d.AttractionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlaceSightseeingLocations_SightseeingLocations");

            entity.HasOne(d => d.Item)
                .WithMany(p => p.ItemAttractions)
                .HasForeignKey(d => d.ItemID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlaceSightseeingLocations_Places");
        });

        modelBuilder.Entity<ItemPicture>(entity =>
        {
            entity.HasOne(d => d.Item)
                .WithMany(p => p.ItemPictures)
                .HasForeignKey(d => d.ItemID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlacePictures_Places");
        });

        modelBuilder.Entity<ItemPrice>(entity =>
        {
            entity.HasOne(d => d.CancellationPolicy)
                .WithMany(p => p.ItemPrices)
                .HasForeignKey(d => d.CancellationPolicyID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlacePrices_CancellationPolicies");

            entity.HasOne(d => d.Item)
                .WithMany(p => p.ItemPrices)
                .HasForeignKey(d => d.ItemID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlacePrices_Places");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasOne(d => d.TransactionType)
                .WithMany(p => p.Transactions)
                .HasForeignKey(d => d.TransactionTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transactions_TransactionTypes");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasOne(d => d.UserType)
                .WithMany(p => p.Users)
                .HasForeignKey(d => d.UserTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_UserTypes");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}