// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class Booking
{
    [Key]
    public long ID { get; set; }

    public Guid GUID { get; set; }

    public long UserID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BookingDate { get; set; }

    public long? CouponID { get; set; }

    public long? TransactionID { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? AmountPaid { get; set; }

    [InverseProperty("Booking")]
    public virtual ICollection<BookingDetail> BookingDetails { get; } = new List<BookingDetail>();

    [ForeignKey("CouponID")]
    [InverseProperty("Bookings")]
    public virtual Coupon Coupon { get; set; }

    [ForeignKey("TransactionID")]
    [InverseProperty("Bookings")]
    public virtual Transaction Transaction { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Bookings")]
    public virtual User User { get; set; }
}