// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class BookingDetail
{
    [Key]
    public long ID { get; set; }

    public Guid GUID { get; set; }

    public long BookingID { get; set; }

    public long ItemPriceID { get; set; }

    public bool isRefund { get; set; }

    [Column(TypeName = "date")]
    public DateTime? RefundDate { get; set; }

    public long? RefundCancellationPoliciyID { get; set; }

    [ForeignKey("BookingID")]
    [InverseProperty("BookingDetails")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("ItemPriceID")]
    [InverseProperty("BookingDetails")]
    public virtual ItemPrice ItemPrice { get; set; }
}