// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class Coupon
{
    [Key]
    public long ID { get; set; }

    public Guid GUID { get; set; }

    [Required]
    [StringLength(50)]
    public string CouponCode { get; set; }

    [Column(TypeName = "decimal(4, 1)")]
    public decimal DiscountPercent { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal MaximimDiscountAmount { get; set; }

    [InverseProperty("Coupon")]
    public virtual ICollection<Booking> Bookings { get; } = new List<Booking>();
}