// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class DimDate
{
    [Key]
    public long ID { get; set; }

    [Column(TypeName = "date")]
    public DateTime Date { get; set; }

    public int Year { get; set; }

    public int Quarter { get; set; }

    public int Month { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string MonthName { get; set; }

    public int DayOfMonth { get; set; }

    public int DayOfWeek { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string DayName { get; set; }

    public bool isHoliday { get; set; }
}