// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class Item
{
    [Key]
    public long ID { get; set; }

    public Guid GUID { get; set; }

    public long UserID { get; set; }

    public long ItemTypeID { get; set; }

    public long AreaID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Title { get; set; }

    public int Capacity { get; set; }

    public int NumberOfBeds { get; set; }

    public int NumberOfBedrooms { get; set; }

    public int NumberOfBathrooms { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string ExactAddress { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string ApproximateAddress { get; set; }

    [Required]
    [StringLength(2000)]
    public string Description { get; set; }

    [Required]
    [StringLength(2000)]
    public string HostRules { get; set; }

    public int MinimumNights { get; set; }

    public int MaximumNights { get; set; }

    [ForeignKey("AreaID")]
    [InverseProperty("Items")]
    public virtual Area Area { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<ItemAmenity> ItemAmenities { get; } = new List<ItemAmenity>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemAttraction> ItemAttractions { get; } = new List<ItemAttraction>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemPicture> ItemPictures { get; } = new List<ItemPicture>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemPrice> ItemPrices { get; } = new List<ItemPrice>();

    [InverseProperty("Item")]
    public virtual ICollection<ItemScore> ItemScores { get; } = new List<ItemScore>();

    [ForeignKey("ItemTypeID")]
    [InverseProperty("Items")]
    public virtual ItemType ItemType { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Items")]
    public virtual User User { get; set; }
}