// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class ItemScore
{
    [Key]
    public long ID { get; set; }

    public Guid GUID { get; set; }

    public long UserID { get; set; }

    public long ItemID { get; set; }

    public long ScoreID { get; set; }

    public long Value { get; set; }

    [ForeignKey("ItemID")]
    [InverseProperty("ItemScores")]
    public virtual Item Item { get; set; }

    [ForeignKey("ScoreID")]
    [InverseProperty("ItemScores")]
    public virtual Score Score { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("ItemScores")]
    public virtual User User { get; set; }
}