// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class ItemAmenity
{
    [Key]
    public long ID { get; set; }

    public Guid GUID { get; set; }

    public long ItemID { get; set; }

    public long AmenityID { get; set; }

    [ForeignKey("AmenityID")]
    [InverseProperty("ItemAmenities")]
    public virtual Amenity Amenity { get; set; }

    [ForeignKey("ItemID")]
    [InverseProperty("ItemAmenities")]
    public virtual Item Item { get; set; }
}