// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session4.Infra.Models;

public partial class Transaction
{
    [Key]
    public long ID { get; set; }

    public Guid GUID { get; set; }

    public long UserID { get; set; }

    public long TransactionTypeID { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "date")]
    public DateTime TransactionDate { get; set; }

    [Required]
    [StringLength(50)]
    public string GatewayReturnID { get; set; }

    [InverseProperty("Transaction")]
    public virtual ICollection<Booking> Bookings { get; } = new List<Booking>();

    [ForeignKey("TransactionTypeID")]
    [InverseProperty("Transactions")]
    public virtual TransactionType TransactionType { get; set; }
}