//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendum
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> nulo { get; set; }
    }
}
