//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S4.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdAbuDhabiTurS04Entities : DbContext
    {
        public bdAbuDhabiTurS04Entities()
            : base("name=bdAbuDhabiTurS04Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<DisponibilidadeAcomodacao> DisponibilidadeAcomodacaos { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<TIPOACOMODACAO> TIPOACOMODACAOs { get; set; }
        public virtual DbSet<Agendum> Agenda1 { get; set; }
    }
}
