//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessa03Aparamento.BancoDeDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartamento()
        {
            this.FotosApartamento = new HashSet<FotosApartamento>();
            this.ItensAdicionais = new HashSet<ItensAdicionais>();
            this.Manutencao = new HashSet<Manutencao>();
        }
    
        public string Codigo { get; set; }
        public int CodigoTipo { get; set; }
        public bool Ativo { get; set; }
        public int Leitos { get; set; }
        public int QtdQuartos { get; set; }
        public int CodigoResponsavel { get; set; }
        public int CodigoProprietario { get; set; }
        public Nullable<int> Andar { get; set; }
        public byte[] Video { get; set; }
    
        public virtual Proprietario Proprietario { get; set; }
        public virtual Responsavel Responsavel { get; set; }
        public virtual Tipo Tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotosApartamento> FotosApartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensAdicionais> ItensAdicionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manutencao> Manutencao { get; set; }
    }
}
