//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessa03Aparamento.BancoDeDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensAdicionais
    {
        public string CodigoApartamento { get; set; }
        public int CodigoProduto { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Apartamento Apartamento { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
