//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S4.Banco_de_dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisponibilidadeAcomodacao
    {
        public int DISCOD { get; set; }
        public System.DateTime DISDATA { get; set; }
        public int DISQUANTIDADE { get; set; }
        public Nullable<int> TIPCODIGO { get; set; }
        public Nullable<decimal> VALOR1 { get; set; }
        public Nullable<decimal> VALOR2 { get; set; }
        public Nullable<decimal> VALOR3 { get; set; }
        public Nullable<decimal> VALOR4 { get; set; }
        public Nullable<decimal> VALOR5 { get; set; }
        public Nullable<int> MINIMO { get; set; }
    
        public virtual TIPOACOMODACAO TIPOACOMODACAO { get; set; }
    }
}
