//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017_S4.Banco_de_dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.TIPOACOMODACAO = new HashSet<TIPOACOMODACAO>();
        }
    
        public int HOTCODIGO { get; set; }
        public string HOTNOME { get; set; }
        public string HOTENDERECO { get; set; }
        public string HOTFOTO { get; set; }
        public bool CAFEINCLUSO { get; set; }
        public bool WIFI { get; set; }
        public bool ESTACIONAMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPOACOMODACAO> TIPOACOMODACAO { get; set; }
    }
}
