//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Compras = new HashSet<Compra>();
        }
    
        public int CODIGO { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string CPF { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime DATANASCIMENTO { get; set; }
        public string ENDERECO { get; set; }
        public string CIDADE { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string Feedback { get; set; }
    
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compras { get; set; }
    }
}
