//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int CODIGO { get; set; }
        public Nullable<int> CODIGOCLIENTE { get; set; }
        public Nullable<decimal> VALORBRUTO { get; set; }
        public Nullable<decimal> DESCONTOS { get; set; }
        public Nullable<decimal> VALORLIQUIDO { get; set; }
        public string ACOMPANHANTES { get; set; }
        public string TRANSACAOID { get; set; }
        public System.DateTime DATA { get; set; }
        public Nullable<System.DateTime> DATAATUALIZACAO { get; set; }
        public string STATUS { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
