//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT09SELETIVAWSC2017.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int CODIGO { get; set; }
        public int CODIGOCOMPRA { get; set; }
        public int CODIGOTIPO { get; set; }
        public System.DateTime DATAINICIO { get; set; }
        public System.DateTime DATAFIM { get; set; }
        public string TIPOPENSAO { get; set; }
        public Nullable<int> QUANTIDADEADULTOS { get; set; }
        public Nullable<int> QUANTIDADECRIANCAS { get; set; }
        public Nullable<decimal> VALORRESERVA { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual TIPOACOMODACAO TIPOACOMODACAO { get; set; }
    }
}
