//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT_01_SEv3.Forms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class departamentos_
    {
        public int Id { get; set; }
        public string deptname { get; set; }
        public Nullable<int> deptmgrid { get; set; }

        public funcionarios_ Funcionario { get; set; }
    }
}
