//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT_01_SEv3.Forms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class funcionarios_
    {
        public int Id { get; set; }
        public Nullable<int> mgrid { get; set; }
        public string empname { get; set; }
        public float salary { get; set; }
        public int deptid { get; set; } 

        public funcionarios_ Funcionario { get; set; }
        public logins_ Login { get; set; }
        public nascimento_ Nascimento { get; set; }
    }
}
