//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT_01_SEv2.Forms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departamentos()
        {
            this.FuncionariosDepartamentos = new HashSet<FuncionariosDepartamentos>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> GerenteId { get; set; }
    
        public virtual Funcionarios Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncionariosDepartamentos> FuncionariosDepartamentos { get; set; }
    }
}
