//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT_01_SEv2.Forms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionariosDepartamentos
    {
        public int Id { get; set; }
        public int FuncionarioId { get; set; }
        public int DepartamentoId { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
    }
}
