//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT_01_SEv2.Forms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int Id { get; set; }
        public Nullable<double> empid { get; set; }
        public Nullable<double> mgrid { get; set; }
        public string empname { get; set; }
        public decimal salary { get; set; }
        public double depid { get; set; }
        public string deptname { get; set; }
        public Nullable<double> deptmgrid { get; set; }
    }
}
