//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT_01_SEv2.Forms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class nascimento_
    {
        public int Id { get; set; }
        public Nullable<double> empid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
    }
}
