// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session1.Infra.Models
{
    public partial class Amenity
    {
        public Amenity()
        {
            ItemAmenities = new HashSet<ItemAmenity>();
        }

        [Key]
        public long ID { get; set; }
        public Guid GUID { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string IconName { get; set; }

        [InverseProperty("Amenity")]
        public virtual ICollection<ItemAmenity> ItemAmenities { get; set; }
    }
}