// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session1.Infra.Models
{
    public partial class Attraction
    {
        public Attraction()
        {
            ItemAttractions = new HashSet<ItemAttraction>();
        }

        [Key]
        public long ID { get; set; }
        public Guid GUID { get; set; }
        public long AreaID { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Address { get; set; }

        [ForeignKey("AreaID")]
        [InverseProperty("Attractions")]
        public virtual Area Area { get; set; }
        [InverseProperty("Attraction")]
        public virtual ICollection<ItemAttraction> ItemAttractions { get; set; }
    }
}