// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session1.Infra.Models
{
    public partial class CancellationPolicy
    {
        public CancellationPolicy()
        {
            CancellationRefundFees = new HashSet<CancellationRefundFee>();
            ItemPrices = new HashSet<ItemPrice>();
        }

        [Key]
        public long ID { get; set; }
        public Guid GUID { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal Commission { get; set; }

        [InverseProperty("CancellationPolicy")]
        public virtual ICollection<CancellationRefundFee> CancellationRefundFees { get; set; }
        [InverseProperty("CancellationPolicy")]
        public virtual ICollection<ItemPrice> ItemPrices { get; set; }
    }
}