// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session1.Infra.Models
{
    public partial class CancellationRefundFee
    {
        [Key]
        public long ID { get; set; }
        public Guid GUID { get; set; }
        public long CancellationPolicyID { get; set; }
        public int DaysLeft { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal PenaltyPercentage { get; set; }

        [ForeignKey("CancellationPolicyID")]
        [InverseProperty("CancellationRefundFees")]
        public virtual CancellationPolicy CancellationPolicy { get; set; }
    }
}