// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session1.Infra.Models
{
    public partial class ItemPrice
    {
        [Key]
        public long ID { get; set; }
        public Guid GUID { get; set; }
        public long ItemID { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Price { get; set; }
        public long CancellationPolicyID { get; set; }

        [ForeignKey("CancellationPolicyID")]
        [InverseProperty("ItemPrices")]
        public virtual CancellationPolicy CancellationPolicy { get; set; }
        [ForeignKey("ItemID")]
        [InverseProperty("ItemPrices")]
        public virtual Item Item { get; set; }
    }
}