// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Session1.Infra.Models
{
    public partial class User
    {
        public User()
        {
            Items = new HashSet<Item>();
        }

        [Key]
        public long ID { get; set; }
        public Guid GUID { get; set; }
        public long UserTypeID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Username { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Password { get; set; }
        [Required]
        [StringLength(50)]
        public string FullName { get; set; }
        public bool Gender { get; set; }
        [Column(TypeName = "date")]
        public DateTime BirthDate { get; set; }
        public int FamilyCount { get; set; }

        [ForeignKey("UserTypeID")]
        [InverseProperty("Users")]
        public virtual UserType UserType { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Item> Items { get; set; }
    }
}