// <auto-generated />
using System;
using MPT_01_SEv1.WinApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MPT01SEv1.WinApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230126194916_Infra")]
    partial class Infra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MPT_01_SEv1.WinApp.Modelos.Departamento.Model", b =>
                {
                    b.Property<int>("depid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("depid"));

                    b.Property<int?>("deptmgrid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("depid");

                    b.HasIndex("deptmgrid")
                        .IsUnique()
                        .HasFilter("[deptmgrid] IS NOT NULL");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("MPT_01_SEv1.WinApp.Modelos.Funcionario.Model", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empid"));

                    b.Property<int>("VezesNoSistema")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("depid")
                        .HasColumnType("int");

                    b.Property<int?>("deptmgrid")
                        .HasColumnType("int");

                    b.Property<string>("deptname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("gerente")
                        .HasColumnType("bit");

                    b.Property<int?>("mgrid")
                        .HasColumnType("int");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.HasKey("empid");

                    b.HasIndex("mgrid");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("MPT_01_SEv1.WinApp.Modelos.Departamento.Model", b =>
                {
                    b.HasOne("MPT_01_SEv1.WinApp.Modelos.Funcionario.Model", "Gerente")
                        .WithOne("DepartamentoModel")
                        .HasForeignKey("MPT_01_SEv1.WinApp.Modelos.Departamento.Model", "deptmgrid");

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("MPT_01_SEv1.WinApp.Modelos.Funcionario.Model", b =>
                {
                    b.HasOne("MPT_01_SEv1.WinApp.Modelos.Funcionario.Model", "Gerente")
                        .WithMany()
                        .HasForeignKey("mgrid");

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("MPT_01_SEv1.WinApp.Modelos.Funcionario.Model", b =>
                {
                    b.Navigation("DepartamentoModel");
                });
#pragma warning restore 612, 618
        }
    }
}
