//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetTheStartup_v2.Forms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaParticipante
    {
        public int Id { get; set; }
        public int VisitaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Visita Visita { get; set; }
    }
}
