//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetTheStartup_v2.Forms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.GaleriaImagens = new HashSet<GaleriaImagen>();
            this.ListaEsperas = new HashSet<ListaEspera>();
            this.ListaParticipantes = new HashSet<ListaParticipante>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string NomeLogin { get; set; }
        public string Senha { get; set; }
        public int GaleriaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GaleriaImagen> GaleriaImagens { get; set; }
        public virtual GaleriaImagen GaleriaImagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaEspera> ListaEsperas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaParticipante> ListaParticipantes { get; set; }
    }
}
